# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\35480\Desktop\python\AUSCOJ\AmongUsSc\usersSettingUI\uiFile\gitSubmitClone.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 464)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CardWidget_push = CardWidget(Form)
        self.CardWidget_push.setObjectName("CardWidget_push")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CardWidget_push)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubtitleLabel_push = SubtitleLabel(self.CardWidget_push)
        self.SubtitleLabel_push.setObjectName("SubtitleLabel_push")
        self.verticalLayout_2.addWidget(self.SubtitleLabel_push)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.BodyLabel_submit = BodyLabel(self.CardWidget_push)
        self.BodyLabel_submit.setObjectName("BodyLabel_submit")
        self.verticalLayout_2.addWidget(self.BodyLabel_submit)
        self.LineEdit_submit = LineEdit(self.CardWidget_push)
        self.LineEdit_submit.setObjectName("LineEdit_submit")
        self.verticalLayout_2.addWidget(self.LineEdit_submit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.PrimaryPushButton_push = PrimaryPushButton(self.CardWidget_push)
        self.PrimaryPushButton_push.setObjectName("PrimaryPushButton_push")
        self.verticalLayout_2.addWidget(self.PrimaryPushButton_push)
        self.horizontalLayout.addWidget(self.CardWidget_push)
        self.CardWidget_clone = CardWidget(Form)
        self.CardWidget_clone.setObjectName("CardWidget_clone")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CardWidget_clone)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubtitleLabel_clone = SubtitleLabel(self.CardWidget_clone)
        self.SubtitleLabel_clone.setObjectName("SubtitleLabel_clone")
        self.verticalLayout_3.addWidget(self.SubtitleLabel_clone)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.BodyLabel_new_submit = BodyLabel(self.CardWidget_clone)
        self.BodyLabel_new_submit.setObjectName("BodyLabel_new_submit")
        self.verticalLayout_3.addWidget(self.BodyLabel_new_submit)
        self.LineEdit_new_submit = LineEdit(self.CardWidget_clone)
        self.LineEdit_new_submit.setReadOnly(True)
        self.LineEdit_new_submit.setObjectName("LineEdit_new_submit")
        self.verticalLayout_3.addWidget(self.LineEdit_new_submit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.PushButton_clone = PushButton(self.CardWidget_clone)
        self.PushButton_clone.setObjectName("PushButton_clone")
        self.verticalLayout_3.addWidget(self.PushButton_clone)
        self.horizontalLayout.addWidget(self.CardWidget_clone)
        self.CardWidget_log = CardWidget(Form)
        self.CardWidget_log.setObjectName("CardWidget_log")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CardWidget_log)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SubtitleLabel_log = SubtitleLabel(self.CardWidget_log)
        self.SubtitleLabel_log.setObjectName("SubtitleLabel_log")
        self.verticalLayout_4.addWidget(self.SubtitleLabel_log)
        self.TextEdit_log = TextEdit(self.CardWidget_log)
        self.TextEdit_log.setObjectName("TextEdit_log")
        self.verticalLayout_4.addWidget(self.TextEdit_log)
        self.horizontalLayout.addWidget(self.CardWidget_log)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "git操作"))
        self.SubtitleLabel_push.setText(_translate("Form", "发送数据"))
        self.BodyLabel_submit.setText(_translate("Form", "提交信息"))
        self.LineEdit_submit.setText(_translate("Form", " Update User Data (20xx/xx/xx xx:xx) "))
        self.LineEdit_submit.setPlaceholderText(_translate("Form", "请输入提交时的信息"))
        self.PrimaryPushButton_push.setText(_translate("Form", "提交+发送"))
        self.SubtitleLabel_clone.setText(_translate("Form", "克隆仓库"))
        self.BodyLabel_new_submit.setText(_translate("Form", "最新的提交信息"))
        self.PushButton_clone.setText(_translate("Form", "克隆！"))
        self.SubtitleLabel_log.setText(_translate("Form", "git输出"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PrimaryPushButton, PushButton, SubtitleLabel, TextEdit
